// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Create20191227 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create20191227));
        
        string IMigrationMetadata.Id
        {
            get { return "201906240646379_Create20191227"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
